version: 0.2
phases: 
  pre_build: 
    commands:
      - npm install
      - npm install -g hexo 
  build:
    commands:
      - hexo generate
  post_build:
    commands:
      - aws s3 sync public/ s3://simalab-app-sample-blog/ --delete